//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicantPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppCollegeMaster
    {
        public int AppCollegeId { get; set; }
        public int ApllicationId { get; set; }
        public int DistrictId { get; set; }
        public int CollegeId { get; set; }
        public int StremId { get; set; }
    }
}
