//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicantPortal.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StudAppDBEntities : DbContext
    {
        public StudAppDBEntities()
            : base("name=StudAppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppCollegeMaster> AppCollegeMasters { get; set; }
        public virtual DbSet<ApplicationMaster> ApplicationMasters { get; set; }
        public virtual DbSet<BlockMaster> BlockMasters { get; set; }
        public virtual DbSet<BloodGroupMaster> BloodGroupMasters { get; set; }
        public virtual DbSet<BoardMaster> BoardMasters { get; set; }
        public virtual DbSet<CollegeMaster> CollegeMasters { get; set; }
        public virtual DbSet<DistrictMaster> DistrictMasters { get; set; }
        public virtual DbSet<GenderMaster> GenderMasters { get; set; }
        public virtual DbSet<MotherToungeMaster> MotherToungeMasters { get; set; }
        public virtual DbSet<NationalityMaster> NationalityMasters { get; set; }
        public virtual DbSet<ReligionMaster> ReligionMasters { get; set; }
        public virtual DbSet<StateMaster> StateMasters { get; set; }
        public virtual DbSet<StreamMaster> StreamMasters { get; set; }
        public virtual DbSet<YearMaster> YearMasters { get; set; }
        public virtual DbSet<ApplicantSubject> ApplicantSubjects { get; set; }
        public virtual DbSet<SectionMaster> SectionMasters { get; set; }
        public virtual DbSet<SubjectMaster> SubjectMasters { get; set; }
    
        public virtual int GetAutoCompleteData(string keyword, Nullable<int> count, string tableName, string displayColumnName, string valueColumnName, string whereClause, string type)
        {
            var keywordParameter = keyword != null ?
                new ObjectParameter("Keyword", keyword) :
                new ObjectParameter("Keyword", typeof(string));
    
            var countParameter = count.HasValue ?
                new ObjectParameter("Count", count) :
                new ObjectParameter("Count", typeof(int));
    
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            var displayColumnNameParameter = displayColumnName != null ?
                new ObjectParameter("DisplayColumnName", displayColumnName) :
                new ObjectParameter("DisplayColumnName", typeof(string));
    
            var valueColumnNameParameter = valueColumnName != null ?
                new ObjectParameter("ValueColumnName", valueColumnName) :
                new ObjectParameter("ValueColumnName", typeof(string));
    
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetAutoCompleteData", keywordParameter, countParameter, tableNameParameter, displayColumnNameParameter, valueColumnNameParameter, whereClauseParameter, typeParameter);
        }
    }
}
